CREATE TABLE IF NOT EXISTS portal_users (
 email VARCHAR(190) PRIMARY KEY,
 password_hash VARCHAR(255) NOT NULL,
 profile LONGTEXT NOT NULL,
 active TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS portal_state (
 id TINYINT PRIMARY KEY,
 revision BIGINT NOT NULL DEFAULT 0,
 data LONGTEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO portal_state (id,data) VALUES (1,'{}');
CREATE TABLE IF NOT EXISTS portal_login_limits (
 bucket CHAR(64) PRIMARY KEY,
 attempts INT NOT NULL DEFAULT 0,
 started BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
